export const TRACK_SUBJECT = 'TRACK_SUBJECT'
export const TWEETS_RECEIVED = 'TWEETS_RECEIVED'
export const READ_ALL_TWEETS = 'READ_ALL_TWEETS'
export const VIEW_MORE_TWEETS = 'VIEW_MORE_TWEETS'
export const UNTRACK_SUBJECT = 'UNTRACK_SUBJECT'

